<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // You can customize this data as per your requirements
        $municipalities = [
            // Abra
            // ['id' => 1, 'name' => 'Bangued', 'province_id' => 1],
            // ['id' => 2, 'name' => 'Boliney', 'province_id' => 1],
            // ['id' => 3, 'name' => 'Bucay', 'province_id' => 1],
            // ['id' => 4, 'name' => 'Bucloc', 'province_id' => 1],
            // ['id' => 5, 'name' => 'Daguioman', 'province_id' => 1],
            // ['id' => 6, 'name' => 'Danglas', 'province_id' => 1],
            // ['id' => 7, 'name' => 'Dolores', 'province_id' => 1],
            // ['id' => 8, 'name' => 'La Paz', 'province_id' => 1],
            // ['id' => 9, 'name' => 'Lacub', 'province_id' => 1],
            // ['id' => 10, 'name' => 'Lagangilang', 'province_id' => 1],
            // ['id' => 11, 'name' => 'Lagayan', 'province_id' => 1],
            // ['id' => 12, 'name' => 'Langiden', 'province_id' => 1],
            // ['id' => 13, 'name' => 'Licuan-Baay', 'province_id' => 1],
            // ['id' => 14, 'name' => 'Luba', 'province_id' => 1],
            // ['id' => 15, 'name' => 'Malibcong', 'province_id' => 1],
            // ['id' => 16, 'name' => 'Manabo', 'province_id' => 1],
            // ['id' => 17, 'name' => 'Peñarrubia', 'province_id' => 1],
            // ['id' => 18, 'name' => 'Pidigan', 'province_id' => 1],
            // ['id' => 19, 'name' => 'Pilar', 'province_id' => 1],
            // ['id' => 20, 'name' => 'Sallapadan', 'province_id' => 1],
            // ['id' => 21, 'name' => 'San Isidro', 'province_id' => 1],
            // ['id' => 22, 'name' => 'San Juan', 'province_id' => 1],
            // ['id' => 23, 'name' => 'San Quintin', 'province_id' => 1],
            // ['id' => 24, 'name' => 'Tayum', 'province_id' => 1],
            // ['id' => 25, 'name' => 'Tineg', 'province_id' => 1],
            // ['id' => 26, 'name' => 'Tubo', 'province_id' => 1],
            // ['id' => 27, 'name' => 'Villaviciosa', 'province_id' => 1],
            // // Agusan del Norte
            // ['id' => 28, 'name' => 'Buenavista', 'province_id' => 2],
            // ['id' => 29, 'name' => 'Butuan City', 'province_id' => 2],
            // ['id' => 30, 'name' => 'Cabadbaran', 'province_id' => 2],
            // ['id' => 31, 'name' => 'Carmen', 'province_id' => 2],
            // ['id' => 32, 'name' => 'Jabonga', 'province_id' => 2],
            // ['id' => 33, 'name' => 'Kitcharao', 'province_id' => 2],
            // ['id' => 34, 'name' => 'Las Nieves', 'province_id' => 2],
            // ['id' => 35, 'name' => 'Magallanes', 'province_id' => 2],
            // ['id' => 36, 'name' => 'Nasipit', 'province_id' => 2],
            // ['id' => 37, 'name' => 'Remedios T. Romualdez', 'province_id' => 2],
            // ['id' => 38, 'name' => 'Santiago', 'province_id' => 2],
            // ['id' => 39, 'name' => 'Tubay', 'province_id' => 2],
            // // Agusan del Sur
            // ['id' => 40, 'name' => 'Bayugan', 'province_id' => 3],
            // ['id' => 41, 'name' => 'Bunawan', 'province_id' => 3],
            // ['id' => 42, 'name' => 'Esperanza', 'province_id' => 3],
            // ['id' => 43, 'name' => 'La Paz', 'province_id' => 3],
            // ['id' => 44, 'name' => 'Loreto', 'province_id' => 3],
            // ['id' => 45, 'name' => 'Prosperidad', 'province_id' => 3],
            // ['id' => 46, 'name' => 'Rosario', 'province_id' => 3],
            // ['id' => 47, 'name' => 'San Francisco', 'province_id' => 3],
            // ['id' => 48, 'name' => 'San Luis', 'province_id' => 3],
            // ['id' => 49, 'name' => 'Santa Josefa', 'province_id' => 3],
            // ['id' => 50, 'name' => 'Sibagat', 'province_id' => 3],
            // ['id' => 51, 'name' => 'Talacogon', 'province_id' => 3],
            // ['id' => 52, 'name' => 'Trento', 'province_id' => 3],
            // ['id' => 53, 'name' => 'Veruela', 'province_id' => 3],
            // // Aklan
            // ['id' => 54, 'name' => 'Altavas', 'province_id' => 4],
            // ['id' => 55, 'name' => 'Balete', 'province_id' => 4],
            // ['id' => 56, 'name' => 'Banga', 'province_id' => 4],
            // ['id' => 57, 'name' => 'Batan', 'province_id' => 4],
            // ['id' => 58, 'name' => 'Buruanga', 'province_id' => 4],
            // ['id' => 59, 'name' => 'Ibajay', 'province_id' => 4],
            // ['id' => 60, 'name' => 'Kalibo', 'province_id' => 4],
            // ['id' => 61, 'name' => 'Lezo', 'province_id' => 4],
            // ['id' => 62, 'name' => 'Libacao', 'province_id' => 4],
            // ['id' => 63, 'name' => 'Madalag', 'province_id' => 4],
            // ['id' => 64, 'name' => 'Makato', 'province_id' => 4],
            // ['id' => 65, 'name' => 'Malay', 'province_id' => 4],
            // ['id' => 66, 'name' => 'Malinao', 'province_id' => 4],
            // ['id' => 67, 'name' => 'Nabas', 'province_id' => 4],
            // ['id' => 68, 'name' => 'New Washington', 'province_id' => 4],
            // ['id' => 69, 'name' => 'Numancia', 'province_id' => 4],
            // ['id' => 70, 'name' => 'Tangalan', 'province_id' => 4],
            // Albay
            ['id' => 71, 'name' => 'Bacacay', 'province_id' => 5],
            ['id' => 72, 'name' => 'Camalig', 'province_id' => 5],
            ['id' => 73, 'name' => 'Daraga', 'province_id' => 5],
            ['id' => 74, 'name' => 'Guinobatan', 'province_id' => 5],
            ['id' => 75, 'name' => 'Jovellar', 'province_id' => 5],
            ['id' => 76, 'name' => 'Legazpi City', 'province_id' => 5],
            ['id' => 77, 'name' => 'Libon', 'province_id' => 5],
            ['id' => 78, 'name' => 'Ligao City', 'province_id' => 5],
            ['id' => 79, 'name' => 'Malilipot', 'province_id' => 5],
            ['id' => 80, 'name' => 'Malinao', 'province_id' => 5],
            ['id' => 81, 'name' => 'Manito', 'province_id' => 5],
            ['id' => 82, 'name' => 'Oas', 'province_id' => 5],
            ['id' => 83, 'name' => 'Pio Duran', 'province_id' => 5],
            ['id' => 84, 'name' => 'Polangui', 'province_id' => 5],
            ['id' => 85, 'name' => 'Rapu-Rapu', 'province_id' => 5],
            ['id' => 86, 'name' => 'Santo Domingo', 'province_id' => 5],
            ['id' => 87, 'name' => 'Tabaco City', 'province_id' => 5],
            ['id' => 88, 'name' => 'Tiwi', 'province_id' => 5],
            // // Antique
            // ['id' => 89, 'name' => 'Anini-y', 'province_id' => 6],
            // ['id' => 90, 'name' => 'Barbaza', 'province_id' => 6],
            // ['id' => 91, 'name' => 'Belison', 'province_id' => 6],
            // ['id' => 92, 'name' => 'Bugasong', 'province_id' => 6],
            // ['id' => 93, 'name' => 'Caluya', 'province_id' => 6],
            // ['id' => 94, 'name' => 'Culasi', 'province_id' => 6],
            // ['id' => 95, 'name' => 'Hamtic', 'province_id' => 6],
            // ['id' => 96, 'name' => 'Laua-an', 'province_id' => 6],
            // ['id' => 97, 'name' => 'Libertad', 'province_id' => 6],
            // ['id' => 98, 'name' => 'Pandan', 'province_id' => 6],
            // ['id' => 99, 'name' => 'Patnongon', 'province_id' => 6],
            // ['id' => 100, 'name' => 'San Jose', 'province_id' => 6],
            // ['id' => 101, 'name' => 'San Remigio', 'province_id' => 6],
            // ['id' => 102, 'name' => 'Sebaste', 'province_id' => 6],
            // ['id' => 103, 'name' => 'Sibalom', 'province_id' => 6],
            // ['id' => 104, 'name' => 'Tibiao', 'province_id' => 6],
            // ['id' => 105, 'name' => 'Tobias Fornier', 'province_id' => 6],
            // ['id' => 106, 'name' => 'Valderrama', 'province_id' => 6],
            // // Apayao
            // ['id' => 107, 'name' => 'Conner', 'province_id' => 7],
            // ['id' => 108, 'name' => 'Flora', 'province_id' => 7],
            // ['id' => 109, 'name' => 'Kabugao', 'province_id' => 7],
            // ['id' => 110, 'name' => 'Luna', 'province_id' => 7],
            // ['id' => 111, 'name' => 'Pudtol', 'province_id' => 7],
            // ['id' => 112, 'name' => 'Santa Marcela', 'province_id' => 7],
            // // Aurora
            // ['id' => 113, 'name' => 'Baler', 'province_id' => 8],
            // ['id' => 114, 'name' => 'Casiguran', 'province_id' => 8],
            // ['id' => 115, 'name' => 'Dilasag', 'province_id' => 8],
            // ['id' => 116, 'name' => 'Dinalungan', 'province_id' => 8],
            // ['id' => 117, 'name' => 'Dingalan', 'province_id' => 8],
            // ['id' => 118, 'name' => 'Dipaculao', 'province_id' => 8],
            // ['id' => 119, 'name' => 'Maria Aurora', 'province_id' => 8],
            // ['id' => 120, 'name' => 'San Luis', 'province_id' => 8],
            // // Basilan
            // ['id' => 107, 'name' => 'Akbar', 'province_id' => 9],
            // ['id' => 108, 'name' => 'Al-Barka', 'province_id' => 9],
            // ['id' => 109, 'name' => 'Hadji Mohammad Ajul', 'province_id' => 9],
            // ['id' => 110, 'name' => 'Hadji Muhtamad', 'province_id' => 9],
            // ['id' => 111, 'name' => 'Isabela City', 'province_id' => 9],
            // ['id' => 112, 'name' => 'Lamitan', 'province_id' => 9],
            // ['id' => 113, 'name' => 'Lantawan', 'province_id' => 9],
            // ['id' => 114, 'name' => 'Maluso', 'province_id' => 9],
            // ['id' => 115, 'name' => 'Sumisip', 'province_id' => 9],
            // ['id' => 116, 'name' => 'Tabuan-Lasa', 'province_id' => 9],
            // ['id' => 117, 'name' => 'Tipo-Tipo', 'province_id' => 9],
            // ['id' => 118, 'name' => 'Tuburan', 'province_id' => 9],
            // // Bataan
            // ['id' => 119, 'name' => 'Abucay', 'province_id' => 10],
            // ['id' => 120, 'name' => 'Bagac', 'province_id' => 10],
            // ['id' => 121, 'name' => 'Balanga City', 'province_id' => 10],
            // ['id' => 122, 'name' => 'Dinalupihan', 'province_id' => 10],
            // ['id' => 123, 'name' => 'Hermosa', 'province_id' => 10],
            // ['id' => 124, 'name' => 'Limay', 'province_id' => 10],
            // ['id' => 125, 'name' => 'Mariveles', 'province_id' => 10],
            // ['id' => 126, 'name' => 'Morong', 'province_id' => 10],
            // ['id' => 127, 'name' => 'Orani', 'province_id' => 10],
            // ['id' => 128, 'name' => 'Orion', 'province_id' => 10],
            // ['id' => 129, 'name' => 'Pilar', 'province_id' => 10],
            // ['id' => 130, 'name' => 'Samal', 'province_id' => 10],
            // // Batanes
            // ['id' => 131, 'name' => 'Basco', 'province_id' => 11],
            // ['id' => 132, 'name' => 'Itbayat', 'province_id' => 11],
            // ['id' => 133, 'name' => 'Ivana', 'province_id' => 11],
            // ['id' => 134, 'name' => 'Mahatao', 'province_id' => 11],
            // ['id' => 135, 'name' => 'Sabtang', 'province_id' => 11],
            // ['id' => 136, 'name' => 'Uyugan', 'province_id' => 11],
            // // Batangas
            // ['id' => 137, 'name' => 'Agoncillo', 'province_id' => 12],
            // ['id' => 138, 'name' => 'Alitagtag', 'province_id' => 12],
            // ['id' => 139, 'name' => 'Balayan', 'province_id' => 12],
            // ['id' => 140, 'name' => 'Balete', 'province_id' => 12],
            // ['id' => 141, 'name' => 'Batangas City', 'province_id' => 12],
            // ['id' => 142, 'name' => 'Bauan', 'province_id' => 12],
            // ['id' => 143, 'name' => 'Calaca', 'province_id' => 12],
            // ['id' => 144, 'name' => 'Calatagan', 'province_id' => 12],
            // ['id' => 145, 'name' => 'Cuenca', 'province_id' => 12],
            // ['id' => 146, 'name' => 'Ibaan', 'province_id' => 12],
            // ['id' => 147, 'name' => 'Laurel', 'province_id' => 12],
            // ['id' => 148, 'name' => 'Lemery', 'province_id' => 12],
            // ['id' => 149, 'name' => 'Lian', 'province_id' => 12],
            // ['id' => 150, 'name' => 'Lipa City', 'province_id' => 12],
            // ['id' => 151, 'name' => 'Lobo', 'province_id' => 12],
            // ['id' => 152, 'name' => 'Mabini', 'province_id' => 12],
            // ['id' => 153, 'name' => 'Malvar', 'province_id' => 12],
            // ['id' => 154, 'name' => 'Mataasnakahoy', 'province_id' => 12],
            // ['id' => 155, 'name' => 'Nasugbu', 'province_id' => 12],
            // ['id' => 156, 'name' => 'Padre Garcia', 'province_id' => 12],
            // ['id' => 157, 'name' => 'Rosario', 'province_id' => 12],
            // ['id' => 158, 'name' => 'San Jose', 'province_id' => 12],
            // ['id' => 159, 'name' => 'San Juan', 'province_id' => 12],
            // ['id' => 160, 'name' => 'San Luis', 'province_id' => 12],
            // ['id' => 161, 'name' => 'San Nicolas', 'province_id' => 12],
            // ['id' => 162, 'name' => 'San Pascual', 'province_id' => 12],
            // ['id' => 163, 'name' => 'Santa Teresita', 'province_id' => 12],
            // ['id' => 164, 'name' => 'Santo Tomas', 'province_id' => 12],
            // ['id' => 165, 'name' => 'Taal', 'province_id' => 12],
            // ['id' => 166, 'name' => 'Talisay', 'province_id' => 12],
            // ['id' => 167, 'name' => 'Tanauan City', 'province_id' => 12],
            // ['id' => 168, 'name' => 'Taysan', 'province_id' => 12],
            // ['id' => 169, 'name' => 'Tingloy', 'province_id' => 12],
            // ['id' => 170, 'name' => 'Tuy', 'province_id' => 12],
            // // Benguet
            // ['id' => 171, 'name' => 'Atok', 'province_id' => 13],
            // ['id' => 172, 'name' => 'Baguio City', 'province_id' => 13],
            // ['id' => 173, 'name' => 'Bakun', 'province_id' => 13],
            // ['id' => 174, 'name' => 'Bokod', 'province_id' => 13],
            // ['id' => 175, 'name' => 'Buguias', 'province_id' => 13],
            // ['id' => 176, 'name' => 'Itogon', 'province_id' => 13],
            // ['id' => 177, 'name' => 'Kabayan', 'province_id' => 13],
            // ['id' => 178, 'name' => 'Kapangan', 'province_id' => 13],
            // ['id' => 179, 'name' => 'Kibungan', 'province_id' => 13],
            // ['id' => 180, 'name' => 'La Trinidad', 'province_id' => 13],
            // ['id' => 181, 'name' => 'Mankayan', 'province_id' => 13],
            // ['id' => 182, 'name' => 'Sablan', 'province_id' => 13],
            // ['id' => 183, 'name' => 'Tuba', 'province_id' => 13],
            // ['id' => 184, 'name' => 'Tublay', 'province_id' => 13],
            // // Biliran
            // ['id' => 185, 'name' => 'Almeria', 'province_id' => 14],
            // ['id' => 186, 'name' => 'Biliran', 'province_id' => 14],
            // ['id' => 187, 'name' => 'Cabucgayan', 'province_id' => 14],
            // ['id' => 188, 'name' => 'Caibiran', 'province_id' => 14],
            // ['id' => 189, 'name' => 'Culaba', 'province_id' => 14],
            // ['id' => 190, 'name' => 'Kawayan', 'province_id' => 14],
            // ['id' => 191, 'name' => 'Maripipi', 'province_id' => 14],
            // ['id' => 192, 'name' => 'Naval', 'province_id' => 14],
            // // Bohol
            // ['id' => 193, 'name' => 'Alburquerque', 'province_id' => 15],
            // ['id' => 194, 'name' => 'Alicia', 'province_id' => 15],
            // ['id' => 195, 'name' => 'Anda', 'province_id' => 15],
            // ['id' => 196, 'name' => 'Antequera', 'province_id' => 15],
            // ['id' => 197, 'name' => 'Baclayon', 'province_id' => 15],
            // ['id' => 198, 'name' => 'Balilihan', 'province_id' => 15],
            // ['id' => 199, 'name' => 'Batuan', 'province_id' => 15],
            // ['id' => 200, 'name' => 'Bien Unido', 'province_id' => 15],
            // ['id' => 201, 'name' => 'Bilar', 'province_id' => 15],
            // ['id' => 202, 'name' => 'Buenavista', 'province_id' => 15],
            // ['id' => 203, 'name' => 'Calape', 'province_id' => 15],
            // ['id' => 204, 'name' => 'Candijay', 'province_id' => 15],
            // ['id' => 205, 'name' => 'Carmen', 'province_id' => 15],
            // ['id' => 206, 'name' => 'Catigbian', 'province_id' => 15],
            // ['id' => 207, 'name' => 'Clarin', 'province_id' => 15],
            // ['id' => 208, 'name' => 'Corella', 'province_id' => 15],
            // ['id' => 209, 'name' => 'Cortes', 'province_id' => 15],
            // ['id' => 210, 'name' => 'Dagohoy', 'province_id' => 15],
            // ['id' => 211, 'name' => 'Danao', 'province_id' => 15],
            // ['id' => 212, 'name' => 'Dauis', 'province_id' => 15],
            // ['id' => 213, 'name' => 'Dimiao', 'province_id' => 15],
            // ['id' => 214, 'name' => 'Duero', 'province_id' => 15],
            // ['id' => 215, 'name' => 'Garcia Hernandez', 'province_id' => 15],
            // ['id' => 216, 'name' => 'Guindulman', 'province_id' => 15],
            // ['id' => 217, 'name' => 'Inabanga', 'province_id' => 15],
            // ['id' => 218, 'name' => 'Jagna', 'province_id' => 15],
            // ['id' => 219, 'name' => 'Lila', 'province_id' => 15],
            // ['id' => 220, 'name' => 'Loay', 'province_id' => 15],
            // ['id' => 221, 'name' => 'Loboc', 'province_id' => 15],
            // ['id' => 222, 'name' => 'Loon', 'province_id' => 15],
            // ['id' => 223, 'name' => 'Mabini', 'province_id' => 15],
            // ['id' => 224, 'name' => 'Maribojoc', 'province_id' => 15],
            // ['id' => 225, 'name' => 'Panglao', 'province_id' => 15],
            // ['id' => 226, 'name' => 'Pilar', 'province_id' => 15],
            // ['id' => 227, 'name' => 'Pres. Carlos P. Garcia', 'province_id' => 15],
            // ['id' => 228, 'name' => 'Sagbayan', 'province_id' => 15],
            // ['id' => 229, 'name' => 'San Isidro', 'province_id' => 15],
            // ['id' => 230, 'name' => 'San Miguel', 'province_id' => 15],
            // ['id' => 231, 'name' => 'Sevilla', 'province_id' => 15],
            // ['id' => 232, 'name' => 'Sierra Bullones', 'province_id' => 15],
            // ['id' => 233, 'name' => 'Sikatuna', 'province_id' => 15],
            // ['id' => 234, 'name' => 'Tagbilaran City', 'province_id' => 15],
            // ['id' => 235, 'name' => 'Talibon', 'province_id' => 15],
            // ['id' => 236, 'name' => 'Trinidad', 'province_id' => 15],
            // ['id' => 237, 'name' => 'Tubigon', 'province_id' => 15],
            // ['id' => 238, 'name' => 'Ubay', 'province_id' => 15],
            // ['id' => 239, 'name' => 'Valencia', 'province_id' => 15],
            // // Bukidnon
            // ['id' => 240, 'name' => 'Baungon', 'province_id' => 16],
            // ['id' => 241, 'name' => 'Cabanglasan', 'province_id' => 16],
            // ['id' => 242, 'name' => 'Damulog', 'province_id' => 16],
            // ['id' => 243, 'name' => 'Dangcagan', 'province_id' => 16],
            // ['id' => 244, 'name' => 'Don Carlos', 'province_id' => 16],
            // ['id' => 245, 'name' => 'Impasugong', 'province_id' => 16],
            // ['id' => 246, 'name' => 'Kadingilan', 'province_id' => 16],
            // ['id' => 247, 'name' => 'Kalilangan', 'province_id' => 16],
            // ['id' => 248, 'name' => 'Kibawe', 'province_id' => 16],
            // ['id' => 249, 'name' => 'Kitaotao', 'province_id' => 16],
            // ['id' => 250, 'name' => 'Lantapan', 'province_id' => 16],
            // ['id' => 251, 'name' => 'Libona', 'province_id' => 16],
            // ['id' => 252, 'name' => 'Malaybalay City', 'province_id' => 16],
            // ['id' => 253, 'name' => 'Malitbog', 'province_id' => 16],
            // ['id' => 254, 'name' => 'Manolo Fortich', 'province_id' => 16],
            // ['id' => 255, 'name' => 'Maramag', 'province_id' => 16],
            // ['id' => 256, 'name' => 'Pangantucan', 'province_id' => 16],
            // ['id' => 257, 'name' => 'Quezon', 'province_id' => 16],
            // ['id' => 258, 'name' => 'San Fernando', 'province_id' => 16],
            // ['id' => 259, 'name' => 'Sumilao', 'province_id' => 16],
            // ['id' => 260, 'name' => 'Talakag', 'province_id' => 16],
            // ['id' => 261, 'name' => 'Valencia City', 'province_id' => 16],
            // // Bulacan
            // ['id' => 262, 'name' => 'Angat', 'province_id' => 17],
            // ['id' => 263, 'name' => 'Balagtas', 'province_id' => 17],
            // ['id' => 264, 'name' => 'Baliuag', 'province_id' => 17],
            // ['id' => 265, 'name' => 'Bocaue', 'province_id' => 17],
            // ['id' => 266, 'name' => 'Bulacan', 'province_id' => 17],
            // ['id' => 267, 'name' => 'Bustos', 'province_id' => 17],
            // ['id' => 268, 'name' => 'Calumpit', 'province_id' => 17],
            // ['id' => 269, 'name' => 'Doña Remedios Trinidad', 'province_id' => 17],
            // ['id' => 270, 'name' => 'Guiguinto', 'province_id' => 17],
            // ['id' => 271, 'name' => 'Hagonoy', 'province_id' => 17],
            // ['id' => 272, 'name' => 'Malolos', 'province_id' => 17],
            // ['id' => 273, 'name' => 'Marilao', 'province_id' => 17],
            // ['id' => 274, 'name' => 'Meycauayan', 'province_id' => 17],
            // ['id' => 275, 'name' => 'Norzagaray', 'province_id' => 17],
            // ['id' => 276, 'name' => 'Obando', 'province_id' => 17],
            // ['id' => 277, 'name' => 'Pandi', 'province_id' => 17],
            // ['id' => 278, 'name' => 'Paombong', 'province_id' => 17],
            // ['id' => 279, 'name' => 'Plaridel', 'province_id' => 17],
            // ['id' => 280, 'name' => 'Pulilan', 'province_id' => 17],
            // ['id' => 281, 'name' => 'San Ildefonso', 'province_id' => 17],
            // ['id' => 282, 'name' => 'San Jose del Monte', 'province_id' => 17],
            // ['id' => 283, 'name' => 'San Miguel', 'province_id' => 17],
            // ['id' => 284, 'name' => 'San Rafael', 'province_id' => 17],
            // ['id' => 285, 'name' => 'Santa Maria', 'province_id' => 17],
            // // Cagayan
            // ['id' => 286, 'name' => 'Abulug', 'province_id' => 18],
            // ['id' => 287, 'name' => 'Alcala', 'province_id' => 18],
            // ['id' => 288, 'name' => 'Allacapan', 'province_id' => 18],
            // ['id' => 289, 'name' => 'Amulung', 'province_id' => 18],
            // ['id' => 290, 'name' => 'Aparri', 'province_id' => 18],
            // ['id' => 291, 'name' => 'Baggao', 'province_id' => 18],
            // ['id' => 292, 'name' => 'Ballesteros', 'province_id' => 18],
            // ['id' => 293, 'name' => 'Buguey', 'province_id' => 18],
            // ['id' => 294, 'name' => 'Calayan', 'province_id' => 18],
            // ['id' => 295, 'name' => 'Camalaniugan', 'province_id' => 18],
            // ['id' => 296, 'name' => 'Claveria', 'province_id' => 18],
            // ['id' => 297, 'name' => 'Enrile', 'province_id' => 18],
            // ['id' => 298, 'name' => 'Gattaran', 'province_id' => 18],
            // ['id' => 299, 'name' => 'Gonzaga', 'province_id' => 18],
            // ['id' => 300, 'name' => 'Iguig', 'province_id' => 18],
            // ['id' => 301, 'name' => 'Lal-lo', 'province_id' => 18],
            // ['id' => 302, 'name' => 'Lasam', 'province_id' => 18],
            // ['id' => 303, 'name' => 'Pamplona', 'province_id' => 18],
            // ['id' => 304, 'name' => 'Peñablanca', 'province_id' => 18],
            // ['id' => 305, 'name' => 'Piat', 'province_id' => 18],
            // ['id' => 306, 'name' => 'Rizal', 'province_id' => 18],
            // ['id' => 307, 'name' => 'Sanchez-Mira', 'province_id' => 18],
            // ['id' => 308, 'name' => 'Santa Ana', 'province_id' => 18],
            // ['id' => 309, 'name' => 'Santa Praxedes', 'province_id' => 18],
            // ['id' => 310, 'name' => 'Santa Teresita', 'province_id' => 18],
            // ['id' => 311, 'name' => 'Santo Niño', 'province_id' => 18],
            // ['id' => 312, 'name' => 'Solana', 'province_id' => 18],
            // ['id' => 313, 'name' => 'Tuao', 'province_id' => 18],
            // ['id' => 314, 'name' => 'Tuguegarao City', 'province_id' => 18],
            // Camarines Norte
            ['id' => 315, 'name' => 'Basud', 'province_id' => 19],
            ['id' => 316, 'name' => 'Capalonga', 'province_id' => 19],
            ['id' => 317, 'name' => 'Daet', 'province_id' => 19],
            ['id' => 318, 'name' => 'Jose Panganiban', 'province_id' => 19],
            ['id' => 319, 'name' => 'Labo', 'province_id' => 19],
            ['id' => 320, 'name' => 'Mercedes', 'province_id' => 19],
            ['id' => 321, 'name' => 'Paracale', 'province_id' => 19],
            ['id' => 322, 'name' => 'San Lorenzo Ruiz', 'province_id' => 19],
            ['id' => 323, 'name' => 'San Vicente', 'province_id' => 19],
            ['id' => 324, 'name' => 'Santa Elena', 'province_id' => 19],
            ['id' => 325, 'name' => 'Talisay', 'province_id' => 19],
            ['id' => 326, 'name' => 'Vinzons', 'province_id' => 19],
            // Camarines Sur
            ['id' => 327, 'name' => 'Baao', 'province_id' => 20],
            ['id' => 328, 'name' => 'Balatan', 'province_id' => 20],
            ['id' => 329, 'name' => 'Bato', 'province_id' => 20],
            ['id' => 330, 'name' => 'Bombon', 'province_id' => 20],
            ['id' => 331, 'name' => 'Buhi', 'province_id' => 20],
            ['id' => 332, 'name' => 'Bula', 'province_id' => 20],
            ['id' => 333, 'name' => 'Cabusao', 'province_id' => 20],
            ['id' => 334, 'name' => 'Calabanga', 'province_id' => 20],
            ['id' => 335, 'name' => 'Camaligan', 'province_id' => 20],
            ['id' => 336, 'name' => 'Canaman', 'province_id' => 20],
            ['id' => 337, 'name' => 'Caramoan', 'province_id' => 20],
            ['id' => 338, 'name' => 'Del Gallego', 'province_id' => 20],
            ['id' => 339, 'name' => 'Gainza', 'province_id' => 20],
            ['id' => 340, 'name' => 'Garchitorena', 'province_id' => 20],
            ['id' => 341, 'name' => 'Goa', 'province_id' => 20],
            ['id' => 342, 'name' => 'Iriga City', 'province_id' => 20],
            ['id' => 343, 'name' => 'Lagonoy', 'province_id' => 20],
            ['id' => 344, 'name' => 'Libmanan', 'province_id' => 20],
            ['id' => 345, 'name' => 'Lupi', 'province_id' => 20],
            ['id' => 346, 'name' => 'Magarao', 'province_id' => 20],
            ['id' => 347, 'name' => 'Milaor', 'province_id' => 20],
            ['id' => 348, 'name' => 'Minalabac', 'province_id' => 20],
            ['id' => 349, 'name' => 'Nabua', 'province_id' => 20],
            ['id' => 350, 'name' => 'Naga City', 'province_id' => 20],
            ['id' => 351, 'name' => 'Ocampo', 'province_id' => 20],
            ['id' => 352, 'name' => 'Pamplona', 'province_id' => 20],
            ['id' => 353, 'name' => 'Pasacao', 'province_id' => 20],
            ['id' => 354, 'name' => 'Pili', 'province_id' => 20],
            ['id' => 355, 'name' => 'Presentacion', 'province_id' => 20],
            ['id' => 356, 'name' => 'Ragay', 'province_id' => 20],
            ['id' => 357, 'name' => 'Sagnay', 'province_id' => 20],
            ['id' => 358, 'name' => 'San Fernando', 'province_id' => 20],
            ['id' => 359, 'name' => 'San Jose', 'province_id' => 20],
            ['id' => 360, 'name' => 'Sipocot', 'province_id' => 20],
            ['id' => 361, 'name' => 'Siruma', 'province_id' => 20],
            ['id' => 362, 'name' => 'Tigaon', 'province_id' => 20],
            ['id' => 363, 'name' => 'Tinambac', 'province_id' => 20],
            // // Camiguin
            // ['id' => 364, 'name' => 'Catarman', 'province_id' => 21],
            // ['id' => 365, 'name' => 'Guinsiliban', 'province_id' => 21],
            // ['id' => 366, 'name' => 'Mahinog', 'province_id' => 21],
            // ['id' => 367, 'name' => 'Mambajao', 'province_id' => 21],
            // ['id' => 368, 'name' => 'Sagay', 'province_id' => 21],
            // // Capiz
            // ['id' => 369, 'name' => 'Cuartero', 'province_id' => 22],
            // ['id' => 370, 'name' => 'Dao', 'province_id' => 22],
            // ['id' => 371, 'name' => 'Dumalag', 'province_id' => 22],
            // ['id' => 372, 'name' => 'Dumarao', 'province_id' => 22],
            // ['id' => 373, 'name' => 'Ivisan', 'province_id' => 22],
            // ['id' => 374, 'name' => 'Jamindan', 'province_id' => 22],
            // ['id' => 375, 'name' => 'Maayon', 'province_id' => 22],
            // ['id' => 376, 'name' => 'Mambusao', 'province_id' => 22],
            // ['id' => 377, 'name' => 'Panay', 'province_id' => 22],
            // ['id' => 378, 'name' => 'Panitan', 'province_id' => 22],
            // ['id' => 379, 'name' => 'Pilar', 'province_id' => 22],
            // ['id' => 380, 'name' => 'Pontevedra', 'province_id' => 22],
            // ['id' => 381, 'name' => 'President Roxas', 'province_id' => 22],
            // ['id' => 382, 'name' => 'Roxas City', 'province_id' => 22],
            // ['id' => 383, 'name' => 'Sapi-an', 'province_id' => 22],
            // ['id' => 384, 'name' => 'Sigma', 'province_id' => 22],
            // ['id' => 385, 'name' => 'Tapaz', 'province_id' => 22],
            // Catanduanes
            ['id' => 386, 'name' => 'Bagamanoc', 'province_id' => 23],
            ['id' => 387, 'name' => 'Baras', 'province_id' => 23],
            ['id' => 388, 'name' => 'Bato', 'province_id' => 23],
            ['id' => 389, 'name' => 'Caramoran', 'province_id' => 23],
            ['id' => 390, 'name' => 'Gigmoto', 'province_id' => 23],
            ['id' => 391, 'name' => 'Pandan', 'province_id' => 23],
            ['id' => 392, 'name' => 'Panganiban (Payo)', 'province_id' => 23],
            ['id' => 393, 'name' => 'San Andres (Calolbon)', 'province_id' => 23],
            ['id' => 394, 'name' => 'San Miguel', 'province_id' => 23],
            ['id' => 395, 'name' => 'Viga', 'province_id' => 23],
            ['id' => 396, 'name' => 'Virac', 'province_id' => 23],
            // // Cavite
            // ['id' => 397, 'name' => 'Alfonso', 'province_id' => 24],
            // ['id' => 398, 'name' => 'Amadeo', 'province_id' => 24],
            // ['id' => 399, 'name' => 'Bacoor', 'province_id' => 24],
            // ['id' => 400, 'name' => 'Carmona', 'province_id' => 24],
            // ['id' => 401, 'name' => 'Cavite City', 'province_id' => 24],
            // ['id' => 402, 'name' => 'Dasmariñas', 'province_id' => 24],
            // ['id' => 403, 'name' => 'General Emilio Aguinaldo', 'province_id' => 24],
            // ['id' => 404, 'name' => 'General Mariano Alvarez', 'province_id' => 24],
            // ['id' => 405, 'name' => 'General Trias', 'province_id' => 24],
            // ['id' => 406, 'name' => 'Imus', 'province_id' => 24],
            // ['id' => 407, 'name' => 'Indang', 'province_id' => 24],
            // ['id' => 408, 'name' => 'Kawit', 'province_id' => 24],
            // ['id' => 409, 'name' => 'Magallanes', 'province_id' => 24],
            // ['id' => 410, 'name' => 'Maragondon', 'province_id' => 24],
            // ['id' => 411, 'name' => 'Mendez', 'province_id' => 24],
            // ['id' => 412, 'name' => 'Naic', 'province_id' => 24],
            // ['id' => 413, 'name' => 'Noveleta', 'province_id' => 24],
            // ['id' => 414, 'name' => 'Rosario', 'province_id' => 24],
            // ['id' => 415, 'name' => 'Silang', 'province_id' => 24],
            // ['id' => 416, 'name' => 'Tagaytay', 'province_id' => 24],
            // ['id' => 417, 'name' => 'Tanza', 'province_id' => 24],
            // ['id' => 418, 'name' => 'Ternate', 'province_id' => 24],
            // ['id' => 419, 'name' => 'Trece Martires', 'province_id' => 24],

            //Masbate
            ['id' => 456, 'name' => 'Aroroy', 'province_id' => 48],
            ['id' => 457, 'name' => 'Baleno', 'province_id' => 48],
            ['id' => 458, 'name' => 'Balud', 'province_id' => 48],
            ['id' => 459, 'name' => 'Batuan', 'province_id' => 48],
            ['id' => 460, 'name' => 'Cataingan', 'province_id' => 48],
            ['id' => 461, 'name' => 'Cawayan', 'province_id' => 48],
            ['id' => 462, 'name' => 'Claveria', 'province_id' => 48],
            ['id' => 463, 'name' => 'Dimasalang', 'province_id' => 48],
            ['id' => 464, 'name' => 'Esperanza', 'province_id' => 48],
            ['id' => 465, 'name' => 'Mandaon', 'province_id' => 48],
            ['id' => 466, 'name' => 'Masbate City', 'province_id' => 48],
            ['id' => 467, 'name' => 'Milagros', 'province_id' => 48],
            ['id' => 468, 'name' => 'Mobo', 'province_id' => 48],
            ['id' => 469, 'name' => 'Monreal', 'province_id' => 48],
            ['id' => 470, 'name' => 'Palanas', 'province_id' => 48],
            ['id' => 471, 'name' => 'Pio V. Corpuz', 'province_id' => 48],
            ['id' => 472, 'name' => 'Placer', 'province_id' => 48],
            ['id' => 473, 'name' => 'San Fernando', 'province_id' => 48],
            ['id' => 474, 'name' => 'San Jacinto', 'province_id' => 48],
            ['id' => 475, 'name' => 'San Pascual', 'province_id' => 48],
            ['id' => 476, 'name' => 'Uson', 'province_id' => 48],
            // Sorsogon
            ['id' => 477, 'name' => 'Barcelona', 'province_id' => 69],
            ['id' => 478, 'name' => 'Bulan', 'province_id' => 69],
            ['id' => 479, 'name' => 'Bulusan', 'province_id' => 69],
            ['id' => 480, 'name' => 'Casiguran', 'province_id' => 69],
            ['id' => 481, 'name' => 'Castilla', 'province_id' => 69],
            ['id' => 482, 'name' => 'Donsol', 'province_id' => 69],
            ['id' => 483, 'name' => 'Gubat', 'province_id' => 69],
            ['id' => 484, 'name' => 'Irosin', 'province_id' => 69],
            ['id' => 485, 'name' => 'Juban', 'province_id' => 69],
            ['id' => 486, 'name' => 'Magallanes', 'province_id' => 69],
            ['id' => 487, 'name' => 'Matnog', 'province_id' => 69],
            ['id' => 488, 'name' => 'Pilar', 'province_id' => 69],
            ['id' => 489, 'name' => 'Prieto Diaz', 'province_id' => 69],
            ['id' => 490, 'name' => 'Santa Magdalena', 'province_id' => 69],
            ['id' => 491, 'name' => 'Sorsogon City', 'province_id' => 69],
        ];

        // Insert data into the 'municipalities' table
        DB::table('municipalities')->insert($municipalities);
    }
}
